da =
  signIn: "Log Ind"
  signin: "log ind"
  signOut: "Log Ud"
  signUp: "Opret bruger"
  OR: "Eller"
  forgotPassword: "Glemt?"
  emailAddress: "Email"
  emailResetLink: "Email Reset Link"
  dontHaveAnAccount: "Har du ingen konto?"
  resetYourPassword: "Nulstil kode"
  updateYourPassword: "Ændre din kode"
  password: "Kode"
  usernameOrEmail: "Brugernavn eller email"
  email: "Email"
  ifYouAlreadyHaveAnAccount: "Hvis du allerede har en konto"
  signUpWithYourEmailAddress: "Opret en konto med din email adresse"
  username: "Brugernavm"
  optional: "Valgfri"
  signupCode: "Registreringskode"
  clickAgree: "Ved at oprette acceptere du betingelserne"
  privacyPolicy: "Privatlivs Politik"
  terms: "Brugsbetingelser"
  sign: "Underskriv"
  configure: "Indstil"
  with: "med"
  createAccount: "Opret en konto"
  and: "og"
  "Match failed":  "Match failed"
  "User not found":  "Bruger ikke fundet"

  error:
    minChar: "7 character minimum password."
    pwOneLetter: "Password requires 1 letter."
    pwOneDigit: "Password must have at least one digit."
    usernameRequired: "Username is required."
    emailRequired: "Email is required."
    signupCodeRequired: "Registration code is required."
    signupCodeIncorrect: "Registration code is incorrect."
    signInRequired: "You must be signed in to do that."
    usernameIsEmail: "Username cannot be an email address."

T9n.map "da", da

